// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tcncloud/protoc-gen-state/state/options.proto

package state

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StringFieldOptions struct {
	Create               *string  `protobuf:"bytes,1,opt,name=create" json:"create,omitempty"`
	Get                  *string  `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	List                 *string  `protobuf:"bytes,3,opt,name=list" json:"list,omitempty"`
	Update               *string  `protobuf:"bytes,4,opt,name=update" json:"update,omitempty"`
	Delete               *string  `protobuf:"bytes,5,opt,name=delete" json:"delete,omitempty"`
	Custom               *string  `protobuf:"bytes,6,opt,name=custom" json:"custom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringFieldOptions) Reset()         { *m = StringFieldOptions{} }
func (m *StringFieldOptions) String() string { return proto.CompactTextString(m) }
func (*StringFieldOptions) ProtoMessage()    {}
func (*StringFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c35dc42f402b981, []int{0}
}

func (m *StringFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringFieldOptions.Unmarshal(m, b)
}
func (m *StringFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringFieldOptions.Marshal(b, m, deterministic)
}
func (m *StringFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringFieldOptions.Merge(m, src)
}
func (m *StringFieldOptions) XXX_Size() int {
	return xxx_messageInfo_StringFieldOptions.Size(m)
}
func (m *StringFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StringFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StringFieldOptions proto.InternalMessageInfo

func (m *StringFieldOptions) GetCreate() string {
	if m != nil && m.Create != nil {
		return *m.Create
	}
	return ""
}

func (m *StringFieldOptions) GetGet() string {
	if m != nil && m.Get != nil {
		return *m.Get
	}
	return ""
}

func (m *StringFieldOptions) GetList() string {
	if m != nil && m.List != nil {
		return *m.List
	}
	return ""
}

func (m *StringFieldOptions) GetUpdate() string {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return ""
}

func (m *StringFieldOptions) GetDelete() string {
	if m != nil && m.Delete != nil {
		return *m.Delete
	}
	return ""
}

func (m *StringFieldOptions) GetCustom() string {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return ""
}

type IntFieldOptions struct {
	Create               *int64   `protobuf:"varint,1,opt,name=create" json:"create,omitempty"`
	Get                  *int64   `protobuf:"varint,2,opt,name=get" json:"get,omitempty"`
	List                 *int64   `protobuf:"varint,3,opt,name=list" json:"list,omitempty"`
	Update               *int64   `protobuf:"varint,4,opt,name=update" json:"update,omitempty"`
	Delete               *int64   `protobuf:"varint,5,opt,name=delete" json:"delete,omitempty"`
	Custom               *int64   `protobuf:"varint,6,opt,name=custom" json:"custom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntFieldOptions) Reset()         { *m = IntFieldOptions{} }
func (m *IntFieldOptions) String() string { return proto.CompactTextString(m) }
func (*IntFieldOptions) ProtoMessage()    {}
func (*IntFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c35dc42f402b981, []int{1}
}

func (m *IntFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntFieldOptions.Unmarshal(m, b)
}
func (m *IntFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntFieldOptions.Marshal(b, m, deterministic)
}
func (m *IntFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntFieldOptions.Merge(m, src)
}
func (m *IntFieldOptions) XXX_Size() int {
	return xxx_messageInfo_IntFieldOptions.Size(m)
}
func (m *IntFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_IntFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_IntFieldOptions proto.InternalMessageInfo

func (m *IntFieldOptions) GetCreate() int64 {
	if m != nil && m.Create != nil {
		return *m.Create
	}
	return 0
}

func (m *IntFieldOptions) GetGet() int64 {
	if m != nil && m.Get != nil {
		return *m.Get
	}
	return 0
}

func (m *IntFieldOptions) GetList() int64 {
	if m != nil && m.List != nil {
		return *m.List
	}
	return 0
}

func (m *IntFieldOptions) GetUpdate() int64 {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return 0
}

func (m *IntFieldOptions) GetDelete() int64 {
	if m != nil && m.Delete != nil {
		return *m.Delete
	}
	return 0
}

func (m *IntFieldOptions) GetCustom() int64 {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return 0
}

var E_Msg = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550000,
	Name:          "state.msg",
	Tag:           "bytes,550000,opt,name=msg",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Timeout = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550001,
	Name:          "state.timeout",
	Tag:           "varint,550001,opt,name=timeout",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Retries = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550002,
	Name:          "state.retries",
	Tag:           "varint,550002,opt,name=retries",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*StringFieldOptions)(nil),
	Field:         550003,
	Name:          "state.method",
	Tag:           "bytes,550003,opt,name=method",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_MethodTimeout = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*IntFieldOptions)(nil),
	Field:         550004,
	Name:          "state.method_timeout",
	Tag:           "bytes,550004,opt,name=method_timeout",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_MethodRetries = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*IntFieldOptions)(nil),
	Field:         550005,
	Name:          "state.method_retries",
	Tag:           "bytes,550005,opt,name=method_retries",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_DefaultTimeout = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550006,
	Name:          "state.default_timeout",
	Tag:           "varint,550006,opt,name=default_timeout",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_DefaultRetries = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550007,
	Name:          "state.default_retries",
	Tag:           "varint,550007,opt,name=default_retries",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Debug = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         550008,
	Name:          "state.debug",
	Tag:           "varint,550008,opt,name=debug",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Port = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550010,
	Name:          "state.port",
	Tag:           "varint,550010,opt,name=port",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Debounce = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550011,
	Name:          "state.debounce",
	Tag:           "varint,550011,opt,name=debounce",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_ProtocTsPath = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550012,
	Name:          "state.protoc_ts_path",
	Tag:           "bytes,550012,opt,name=protoc_ts_path",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Hostname = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550013,
	Name:          "state.hostname",
	Tag:           "bytes,550013,opt,name=hostname",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_HostnameLocation = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550014,
	Name:          "state.hostname_location",
	Tag:           "bytes,550014,opt,name=hostname_location",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_AuthTokenLocation = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550015,
	Name:          "state.auth_token_location",
	Tag:           "bytes,550015,opt,name=auth_token_location",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

func init() {
	proto.RegisterType((*StringFieldOptions)(nil), "state.StringFieldOptions")
	proto.RegisterType((*IntFieldOptions)(nil), "state.IntFieldOptions")
	proto.RegisterExtension(E_Msg)
	proto.RegisterExtension(E_Timeout)
	proto.RegisterExtension(E_Retries)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_MethodTimeout)
	proto.RegisterExtension(E_MethodRetries)
	proto.RegisterExtension(E_DefaultTimeout)
	proto.RegisterExtension(E_DefaultRetries)
	proto.RegisterExtension(E_Debug)
	proto.RegisterExtension(E_Port)
	proto.RegisterExtension(E_Debounce)
	proto.RegisterExtension(E_ProtocTsPath)
	proto.RegisterExtension(E_Hostname)
	proto.RegisterExtension(E_HostnameLocation)
	proto.RegisterExtension(E_AuthTokenLocation)
}

func init() {
	proto.RegisterFile("github.com/tcncloud/protoc-gen-state/state/options.proto", fileDescriptor_6c35dc42f402b981)
}

var fileDescriptor_6c35dc42f402b981 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xcb, 0x6e, 0xd3, 0x4e,
	0x14, 0xc6, 0x95, 0xff, 0x24, 0xf9, 0x97, 0x01, 0xd2, 0xd6, 0x48, 0x95, 0x41, 0x20, 0x4a, 0x57,
	0x6c, 0xea, 0xa0, 0xc0, 0x02, 0x86, 0x1d, 0x42, 0x20, 0xc4, 0x55, 0x26, 0x2b, 0x16, 0x58, 0x8e,
	0x7d, 0x3a, 0xb6, 0xb0, 0x3d, 0x96, 0xe7, 0xcc, 0xb3, 0x20, 0xf1, 0x44, 0x3c, 0x0e, 0x77, 0x10,
	0x77, 0x79, 0x2e, 0xa1, 0x6a, 0xd2, 0xda, 0x1b, 0x6b, 0xe6, 0xf8, 0xfb, 0x7d, 0xf3, 0x9d, 0xe3,
	0x91, 0xe9, 0x4d, 0x9e, 0x63, 0xa6, 0x16, 0x41, 0x22, 0xca, 0x29, 0x26, 0x55, 0x52, 0x08, 0x95,
	0x4e, 0xeb, 0x46, 0xa0, 0x48, 0xf6, 0x39, 0x54, 0xfb, 0x12, 0x63, 0x84, 0xa9, 0x79, 0x8a, 0x1a,
	0x73, 0x51, 0xc9, 0x40, 0xbf, 0xf6, 0x46, 0xba, 0x78, 0x61, 0x97, 0x0b, 0xc1, 0x0b, 0x30, 0xcc,
	0x42, 0x1d, 0x4c, 0x53, 0x90, 0x49, 0x93, 0xd7, 0x28, 0x1a, 0x23, 0xdc, 0x7b, 0x33, 0xa0, 0xde,
	0x73, 0x6c, 0xf2, 0x8a, 0xdf, 0xcb, 0xa1, 0x48, 0x9f, 0x1a, 0x17, 0x6f, 0x87, 0x8e, 0x93, 0x06,
	0x62, 0x04, 0x7f, 0xb0, 0x3b, 0xb8, 0x7a, 0x2a, 0xb4, 0x3b, 0x6f, 0x8b, 0x12, 0x0e, 0xe8, 0xff,
	0xa7, 0x8b, 0xed, 0xd2, 0xf3, 0xe8, 0xb0, 0xc8, 0x25, 0xfa, 0x44, 0x97, 0xf4, 0xba, 0xa5, 0x55,
	0x9d, 0xb6, 0xf4, 0xd0, 0xd0, 0x66, 0xd7, 0xd6, 0x53, 0x28, 0x00, 0xc1, 0x1f, 0x99, 0xba, 0xd9,
	0xe9, 0xd3, 0x94, 0x44, 0x51, 0xfa, 0x63, 0x7b, 0x9a, 0xde, 0xed, 0xbd, 0x1e, 0xd0, 0xcd, 0x07,
	0x15, 0x9e, 0x90, 0x8c, 0xac, 0x4b, 0x46, 0x56, 0x93, 0x91, 0xb5, 0xc9, 0xc8, 0x31, 0xc9, 0xc8,
	0x31, 0xc9, 0x88, 0x4b, 0xc6, 0xae, 0x53, 0x52, 0x4a, 0xee, 0x5d, 0x0e, 0xcc, 0x80, 0x03, 0x37,
	0xe0, 0xe0, 0x31, 0x48, 0x19, 0x73, 0xb0, 0x69, 0xfd, 0x77, 0x6f, 0xaf, 0x98, 0x51, 0x95, 0x92,
	0xb3, 0x5b, 0xf4, 0x7f, 0xcc, 0x4b, 0x10, 0x0a, 0xbd, 0x4b, 0x2b, 0xe0, 0xe1, 0x26, 0xfd, 0xf7,
	0x1a, 0x23, 0xa1, 0xd3, 0xb7, 0x68, 0x03, 0xd8, 0xe4, 0x20, 0xbb, 0xd0, 0x0f, 0x0e, 0xb5, 0x7a,
	0x16, 0xd2, 0x71, 0x09, 0x98, 0x89, 0xb4, 0x8b, 0xfc, 0xa8, 0xc9, 0xd3, 0xb3, 0xf3, 0x81, 0xbe,
	0x3c, 0xc1, 0xea, 0xb5, 0x08, 0xad, 0x13, 0x7b, 0x49, 0x27, 0x66, 0x15, 0xf5, 0x6c, 0xe8, 0x93,
	0xf5, 0xde, 0xb1, 0xde, 0x47, 0xbe, 0x6a, 0x78, 0xd6, 0xd8, 0xcd, 0x6d, 0xbb, 0xff, 0xfc, 0x7b,
	0x76, 0xfd, 0xb9, 0x9f, 0x7f, 0x68, 0x67, 0x72, 0x9f, 0x6e, 0xa6, 0x70, 0x10, 0xab, 0x02, 0x97,
	0x0d, 0x5c, 0x5c, 0x73, 0x40, 0xb1, 0xfc, 0x8e, 0x5f, 0xec, 0x54, 0x27, 0x16, 0x73, 0x41, 0x0f,
	0x19, 0xb9, 0xa4, 0x27, 0x1b, 0x7d, 0x3d, 0x62, 0xe4, 0x12, 0xdd, 0xa0, 0xa3, 0x14, 0x16, 0x8a,
	0x77, 0xe0, 0xdf, 0x34, 0xbe, 0x11, 0x1a, 0x31, 0x9b, 0xd1, 0x61, 0x2d, 0x9a, 0xae, 0xf0, 0xdf,
	0xed, 0x99, 0x5a, 0xcb, 0x18, 0xdd, 0x48, 0x61, 0x21, 0x54, 0x95, 0x40, 0x07, 0xf7, 0xc3, 0x72,
	0x4b, 0x3d, 0xbb, 0x4b, 0x27, 0xe6, 0xf7, 0x13, 0xa1, 0x8c, 0xea, 0x18, 0xb3, 0x0e, 0x87, 0x9f,
	0xf6, 0xfa, 0x9f, 0x31, 0xd4, 0x5c, 0x3e, 0x8b, 0x31, 0x6b, 0x13, 0x64, 0x42, 0x62, 0x15, 0x97,
	0x5d, 0x09, 0x7e, 0x59, 0x7e, 0xa9, 0x67, 0x0f, 0xe9, 0xb6, 0x5b, 0x47, 0x85, 0x48, 0xe2, 0x56,
	0xd7, 0x61, 0xf2, 0xdb, 0x9a, 0x6c, 0x39, 0xf0, 0x91, 0xe5, 0xd8, 0x13, 0x7a, 0x2e, 0x56, 0x98,
	0x45, 0x28, 0x5e, 0x41, 0xd5, 0xd7, 0xee, 0x8f, 0xb5, 0xdb, 0x6e, 0xd1, 0x79, 0x4b, 0x3a, 0xbf,
	0x3b, 0xb3, 0x17, 0xd7, 0xfa, 0xff, 0xb1, 0x6f, 0xeb, 0xe7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6a, 0x45, 0x3e, 0x9f, 0xe4, 0x05, 0x00, 0x00,
}
