// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state/options.proto

package state

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateMessageType int32

const (
	StateMessageType_REDUX_STATE   StateMessageType = 0
	StateMessageType_CUSTOM_ACTION StateMessageType = 1
	StateMessageType_EXTERNAL_LINK StateMessageType = 2
)

var StateMessageType_name = map[int32]string{
	0: "REDUX_STATE",
	1: "CUSTOM_ACTION",
	2: "EXTERNAL_LINK",
}

var StateMessageType_value = map[string]int32{
	"REDUX_STATE":   0,
	"CUSTOM_ACTION": 1,
	"EXTERNAL_LINK": 2,
}

func (x StateMessageType) Enum() *StateMessageType {
	p := new(StateMessageType)
	*p = x
	return p
}

func (x StateMessageType) String() string {
	return proto.EnumName(StateMessageType_name, int32(x))
}

func (x *StateMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(StateMessageType_value, data, "StateMessageType")
	if err != nil {
		return err
	}
	*x = StateMessageType(value)
	return nil
}

func (StateMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd31485b9150be4d, []int{0}
}

type OutputTypes int32

const (
	OutputTypes_redux3 OutputTypes = 0
	OutputTypes_redux4 OutputTypes = 1
	OutputTypes_mobx   OutputTypes = 2
)

var OutputTypes_name = map[int32]string{
	0: "redux3",
	1: "redux4",
	2: "mobx",
}

var OutputTypes_value = map[string]int32{
	"redux3": 0,
	"redux4": 1,
	"mobx":   2,
}

func (x OutputTypes) Enum() *OutputTypes {
	p := new(OutputTypes)
	*p = x
	return p
}

func (x OutputTypes) String() string {
	return proto.EnumName(OutputTypes_name, int32(x))
}

func (x *OutputTypes) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OutputTypes_value, data, "OutputTypes")
	if err != nil {
		return err
	}
	*x = OutputTypes(value)
	return nil
}

func (OutputTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dd31485b9150be4d, []int{1}
}

type StringFieldOptions struct {
	Create               *string  `protobuf:"bytes,1,opt,name=create" json:"create,omitempty"`
	Get                  *string  `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	List                 *string  `protobuf:"bytes,3,opt,name=list" json:"list,omitempty"`
	Update               *string  `protobuf:"bytes,4,opt,name=update" json:"update,omitempty"`
	Delete               *string  `protobuf:"bytes,5,opt,name=delete" json:"delete,omitempty"`
	Custom               *string  `protobuf:"bytes,6,opt,name=custom" json:"custom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringFieldOptions) Reset()         { *m = StringFieldOptions{} }
func (m *StringFieldOptions) String() string { return proto.CompactTextString(m) }
func (*StringFieldOptions) ProtoMessage()    {}
func (*StringFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd31485b9150be4d, []int{0}
}

func (m *StringFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringFieldOptions.Unmarshal(m, b)
}
func (m *StringFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringFieldOptions.Marshal(b, m, deterministic)
}
func (m *StringFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringFieldOptions.Merge(m, src)
}
func (m *StringFieldOptions) XXX_Size() int {
	return xxx_messageInfo_StringFieldOptions.Size(m)
}
func (m *StringFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StringFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StringFieldOptions proto.InternalMessageInfo

func (m *StringFieldOptions) GetCreate() string {
	if m != nil && m.Create != nil {
		return *m.Create
	}
	return ""
}

func (m *StringFieldOptions) GetGet() string {
	if m != nil && m.Get != nil {
		return *m.Get
	}
	return ""
}

func (m *StringFieldOptions) GetList() string {
	if m != nil && m.List != nil {
		return *m.List
	}
	return ""
}

func (m *StringFieldOptions) GetUpdate() string {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return ""
}

func (m *StringFieldOptions) GetDelete() string {
	if m != nil && m.Delete != nil {
		return *m.Delete
	}
	return ""
}

func (m *StringFieldOptions) GetCustom() string {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return ""
}

type IntFieldOptions struct {
	Create               *int64   `protobuf:"varint,1,opt,name=create" json:"create,omitempty"`
	Get                  *int64   `protobuf:"varint,2,opt,name=get" json:"get,omitempty"`
	List                 *int64   `protobuf:"varint,3,opt,name=list" json:"list,omitempty"`
	Update               *int64   `protobuf:"varint,4,opt,name=update" json:"update,omitempty"`
	Delete               *int64   `protobuf:"varint,5,opt,name=delete" json:"delete,omitempty"`
	Custom               *int64   `protobuf:"varint,6,opt,name=custom" json:"custom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntFieldOptions) Reset()         { *m = IntFieldOptions{} }
func (m *IntFieldOptions) String() string { return proto.CompactTextString(m) }
func (*IntFieldOptions) ProtoMessage()    {}
func (*IntFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd31485b9150be4d, []int{1}
}

func (m *IntFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntFieldOptions.Unmarshal(m, b)
}
func (m *IntFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntFieldOptions.Marshal(b, m, deterministic)
}
func (m *IntFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntFieldOptions.Merge(m, src)
}
func (m *IntFieldOptions) XXX_Size() int {
	return xxx_messageInfo_IntFieldOptions.Size(m)
}
func (m *IntFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_IntFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_IntFieldOptions proto.InternalMessageInfo

func (m *IntFieldOptions) GetCreate() int64 {
	if m != nil && m.Create != nil {
		return *m.Create
	}
	return 0
}

func (m *IntFieldOptions) GetGet() int64 {
	if m != nil && m.Get != nil {
		return *m.Get
	}
	return 0
}

func (m *IntFieldOptions) GetList() int64 {
	if m != nil && m.List != nil {
		return *m.List
	}
	return 0
}

func (m *IntFieldOptions) GetUpdate() int64 {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return 0
}

func (m *IntFieldOptions) GetDelete() int64 {
	if m != nil && m.Delete != nil {
		return *m.Delete
	}
	return 0
}

func (m *IntFieldOptions) GetCustom() int64 {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return 0
}

type StateMessageOptions struct {
	Type                 *StateMessageType `protobuf:"varint,1,req,name=type,enum=state.StateMessageType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StateMessageOptions) Reset()         { *m = StateMessageOptions{} }
func (m *StateMessageOptions) String() string { return proto.CompactTextString(m) }
func (*StateMessageOptions) ProtoMessage()    {}
func (*StateMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd31485b9150be4d, []int{2}
}

func (m *StateMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateMessageOptions.Unmarshal(m, b)
}
func (m *StateMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateMessageOptions.Marshal(b, m, deterministic)
}
func (m *StateMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateMessageOptions.Merge(m, src)
}
func (m *StateMessageOptions) XXX_Size() int {
	return xxx_messageInfo_StateMessageOptions.Size(m)
}
func (m *StateMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StateMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StateMessageOptions proto.InternalMessageInfo

func (m *StateMessageOptions) GetType() StateMessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return StateMessageType_REDUX_STATE
}

type StateFileOptions struct {
	DefaultTimeout *int64 `protobuf:"varint,1,opt,name=default_timeout,json=defaultTimeout" json:"default_timeout,omitempty"`
	DefaultRetries *int64 `protobuf:"varint,2,opt,name=default_retries,json=defaultRetries" json:"default_retries,omitempty"`
	// turn on debug logging
	Debug *bool `protobuf:"varint,3,opt,name=debug" json:"debug,omitempty"`
	// port to be used for api calls in epics
	Port *int64 `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	// debounce time for api calls in epics
	Debounce *int64 `protobuf:"varint,5,opt,name=debounce" json:"debounce,omitempty"`
	// sets custom import path for proto typescript files
	ProtocTsPath *string `protobuf:"bytes,6,opt,name=protoc_ts_path,json=protocTsPath" json:"protoc_ts_path,omitempty"`
	// static hostname string for api calls
	Hostname *string `protobuf:"bytes,7,opt,name=hostname" json:"hostname,omitempty"`
	// hostname for api calls location in redux
	HostnameLocation *string `protobuf:"bytes,8,opt,name=hostname_location,json=hostnameLocation" json:"hostname_location,omitempty"`
	// add authorization bearer header using the token at this location in redux
	AuthTokenLocation    *string      `protobuf:"bytes,9,opt,name=auth_token_location,json=authTokenLocation" json:"auth_token_location,omitempty"`
	OutputType           *OutputTypes `protobuf:"varint,10,req,name=output_type,json=outputType,enum=state.OutputTypes" json:"output_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *StateFileOptions) Reset()         { *m = StateFileOptions{} }
func (m *StateFileOptions) String() string { return proto.CompactTextString(m) }
func (*StateFileOptions) ProtoMessage()    {}
func (*StateFileOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_dd31485b9150be4d, []int{3}
}

func (m *StateFileOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateFileOptions.Unmarshal(m, b)
}
func (m *StateFileOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateFileOptions.Marshal(b, m, deterministic)
}
func (m *StateFileOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateFileOptions.Merge(m, src)
}
func (m *StateFileOptions) XXX_Size() int {
	return xxx_messageInfo_StateFileOptions.Size(m)
}
func (m *StateFileOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_StateFileOptions.DiscardUnknown(m)
}

var xxx_messageInfo_StateFileOptions proto.InternalMessageInfo

func (m *StateFileOptions) GetDefaultTimeout() int64 {
	if m != nil && m.DefaultTimeout != nil {
		return *m.DefaultTimeout
	}
	return 0
}

func (m *StateFileOptions) GetDefaultRetries() int64 {
	if m != nil && m.DefaultRetries != nil {
		return *m.DefaultRetries
	}
	return 0
}

func (m *StateFileOptions) GetDebug() bool {
	if m != nil && m.Debug != nil {
		return *m.Debug
	}
	return false
}

func (m *StateFileOptions) GetPort() int64 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *StateFileOptions) GetDebounce() int64 {
	if m != nil && m.Debounce != nil {
		return *m.Debounce
	}
	return 0
}

func (m *StateFileOptions) GetProtocTsPath() string {
	if m != nil && m.ProtocTsPath != nil {
		return *m.ProtocTsPath
	}
	return ""
}

func (m *StateFileOptions) GetHostname() string {
	if m != nil && m.Hostname != nil {
		return *m.Hostname
	}
	return ""
}

func (m *StateFileOptions) GetHostnameLocation() string {
	if m != nil && m.HostnameLocation != nil {
		return *m.HostnameLocation
	}
	return ""
}

func (m *StateFileOptions) GetAuthTokenLocation() string {
	if m != nil && m.AuthTokenLocation != nil {
		return *m.AuthTokenLocation
	}
	return ""
}

func (m *StateFileOptions) GetOutputType() OutputTypes {
	if m != nil && m.OutputType != nil {
		return *m.OutputType
	}
	return OutputTypes_redux3
}

var E_StateOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*StateMessageOptions)(nil),
	Field:         550006,
	Name:          "state.state_options",
	Tag:           "bytes,550006,opt,name=state_options",
	Filename:      "state/options.proto",
}

var E_Timeout = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550001,
	Name:          "state.timeout",
	Tag:           "varint,550001,opt,name=timeout",
	Filename:      "state/options.proto",
}

var E_Retries = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550002,
	Name:          "state.retries",
	Tag:           "varint,550002,opt,name=retries",
	Filename:      "state/options.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*StringFieldOptions)(nil),
	Field:         550003,
	Name:          "state.method",
	Tag:           "bytes,550003,opt,name=method",
	Filename:      "state/options.proto",
}

var E_MethodTimeout = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*IntFieldOptions)(nil),
	Field:         550004,
	Name:          "state.method_timeout",
	Tag:           "bytes,550004,opt,name=method_timeout",
	Filename:      "state/options.proto",
}

var E_MethodRetries = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*IntFieldOptions)(nil),
	Field:         550005,
	Name:          "state.method_retries",
	Tag:           "bytes,550005,opt,name=method_retries",
	Filename:      "state/options.proto",
}

var E_StateFileOptions = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*StateFileOptions)(nil),
	Field:         550007,
	Name:          "state.state_file_options",
	Tag:           "bytes,550007,opt,name=state_file_options",
	Filename:      "state/options.proto",
}

func init() {
	proto.RegisterEnum("state.StateMessageType", StateMessageType_name, StateMessageType_value)
	proto.RegisterEnum("state.OutputTypes", OutputTypes_name, OutputTypes_value)
	proto.RegisterType((*StringFieldOptions)(nil), "state.StringFieldOptions")
	proto.RegisterType((*IntFieldOptions)(nil), "state.IntFieldOptions")
	proto.RegisterType((*StateMessageOptions)(nil), "state.StateMessageOptions")
	proto.RegisterType((*StateFileOptions)(nil), "state.StateFileOptions")
	proto.RegisterExtension(E_StateOptions)
	proto.RegisterExtension(E_Timeout)
	proto.RegisterExtension(E_Retries)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_MethodTimeout)
	proto.RegisterExtension(E_MethodRetries)
	proto.RegisterExtension(E_StateFileOptions)
}

func init() { proto.RegisterFile("state/options.proto", fileDescriptor_dd31485b9150be4d) }

var fileDescriptor_dd31485b9150be4d = []byte{
	// 705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x4e, 0xdb, 0x40,
	0x10, 0x26, 0x71, 0x08, 0x61, 0x02, 0xc1, 0x2c, 0x15, 0x75, 0x51, 0xab, 0x52, 0x54, 0xa9, 0x08,
	0x84, 0x53, 0x41, 0x2f, 0x4d, 0x4f, 0x40, 0x83, 0x14, 0x15, 0x48, 0xe5, 0x18, 0x09, 0xf5, 0x50,
	0xcb, 0xb1, 0x17, 0xc7, 0xaa, 0xe3, 0xb5, 0xec, 0xb1, 0x04, 0x4f, 0x52, 0xa9, 0x4f, 0xd4, 0xd7,
	0xe9, 0xff, 0xad, 0xaa, 0xbc, 0xbb, 0x36, 0x06, 0x42, 0xe1, 0x62, 0xed, 0x7c, 0xf3, 0xcd, 0xb7,
	0x33, 0xb3, 0x3b, 0x6b, 0x58, 0x4a, 0xd0, 0x46, 0xda, 0x66, 0x11, 0xfa, 0x2c, 0x4c, 0xf4, 0x28,
	0x66, 0xc8, 0xc8, 0x34, 0x07, 0x57, 0x56, 0x3d, 0xc6, 0xbc, 0x80, 0xb6, 0x39, 0x38, 0x4c, 0xcf,
	0xda, 0x2e, 0x4d, 0x9c, 0xd8, 0x8f, 0x90, 0xc5, 0x82, 0xb8, 0xf6, 0xa5, 0x02, 0x64, 0x80, 0xb1,
	0x1f, 0x7a, 0x07, 0x3e, 0x0d, 0xdc, 0xbe, 0x50, 0x21, 0xcb, 0x50, 0x77, 0x62, 0x6a, 0x23, 0xd5,
	0x2a, 0xab, 0x95, 0xf5, 0x59, 0x43, 0x5a, 0x44, 0x05, 0xc5, 0xa3, 0xa8, 0x55, 0x39, 0x98, 0x2d,
	0x09, 0x81, 0x5a, 0xe0, 0x27, 0xa8, 0x29, 0x1c, 0xe2, 0xeb, 0x2c, 0x3a, 0x8d, 0xdc, 0x2c, 0xba,
	0x26, 0xa2, 0x85, 0x95, 0xe1, 0x2e, 0x0d, 0x28, 0x52, 0x6d, 0x5a, 0xe0, 0xc2, 0xe2, 0xbb, 0xa5,
	0x09, 0xb2, 0xb1, 0x56, 0x97, 0xbb, 0x71, 0x6b, 0xed, 0x73, 0x05, 0x16, 0x7a, 0x21, 0xfe, 0x27,
	0x33, 0x65, 0x52, 0x66, 0xca, 0xcd, 0xcc, 0x94, 0x89, 0x99, 0x29, 0xb7, 0x64, 0xa6, 0xdc, 0x92,
	0x99, 0x52, 0x64, 0xb6, 0x07, 0x4b, 0x83, 0xac, 0xc3, 0x47, 0x34, 0x49, 0x6c, 0x8f, 0xe6, 0xc9,
	0x6d, 0x42, 0x0d, 0x2f, 0xa2, 0x2c, 0xb5, 0xea, 0x7a, 0x6b, 0xfb, 0xa1, 0xce, 0x4f, 0x41, 0x2f,
	0x33, 0xcd, 0x8b, 0x88, 0x1a, 0x9c, 0xb4, 0xf6, 0xb7, 0x0a, 0x2a, 0x77, 0x1d, 0xf8, 0x41, 0xa1,
	0xf0, 0x02, 0x16, 0x5c, 0x7a, 0x66, 0xa7, 0x01, 0x5a, 0xe8, 0x8f, 0x29, 0x4b, 0x51, 0xd6, 0xd9,
	0x92, 0xb0, 0x29, 0xd0, 0x32, 0x31, 0xa6, 0x18, 0xfb, 0x34, 0x91, 0xb5, 0xe7, 0x44, 0x43, 0xa0,
	0xe4, 0x01, 0x4c, 0xbb, 0x74, 0x98, 0x7a, 0xbc, 0x0f, 0x0d, 0x43, 0x18, 0x59, 0x73, 0x22, 0x16,
	0xa3, 0x6c, 0x03, 0x5f, 0x93, 0x15, 0x68, 0xb8, 0x74, 0xc8, 0xd2, 0xd0, 0xc9, 0xdb, 0x50, 0xd8,
	0xe4, 0x39, 0xb4, 0xf8, 0x85, 0x71, 0x2c, 0x4c, 0xac, 0xc8, 0xc6, 0x91, 0x3c, 0xaa, 0x39, 0x81,
	0x9a, 0xc9, 0x7b, 0x1b, 0x47, 0x99, 0xc2, 0x88, 0x25, 0x18, 0xda, 0x63, 0xaa, 0xcd, 0x70, 0x7f,
	0x61, 0x93, 0x4d, 0x58, 0xcc, 0xd7, 0x56, 0xc0, 0x1c, 0x3b, 0xab, 0x57, 0x6b, 0x70, 0x92, 0x9a,
	0x3b, 0x0e, 0x25, 0x4e, 0x74, 0x58, 0xb2, 0x53, 0x1c, 0x59, 0xc8, 0x3e, 0xd1, 0xf0, 0x92, 0x3e,
	0xcb, 0xe9, 0x8b, 0x99, 0xcb, 0xcc, 0x3c, 0x05, 0x7f, 0x07, 0x9a, 0x2c, 0xc5, 0x28, 0x45, 0x8b,
	0xf7, 0x1f, 0x78, 0xff, 0x89, 0xec, 0x7f, 0x9f, 0x7b, 0xb2, 0xce, 0x27, 0x06, 0xb0, 0xc2, 0xd8,
	0xe8, 0xc9, 0xfe, 0x97, 0x8e, 0x86, 0x2c, 0x40, 0xd3, 0xe8, 0xbe, 0x3d, 0x39, 0xb5, 0x06, 0xe6,
	0xae, 0xd9, 0x55, 0xa7, 0xc8, 0x22, 0xcc, 0xef, 0x9f, 0x0c, 0xcc, 0xfe, 0x91, 0xb5, 0xbb, 0x6f,
	0xf6, 0xfa, 0xc7, 0x6a, 0x25, 0x83, 0xba, 0xa7, 0x66, 0xd7, 0x38, 0xde, 0x3d, 0xb4, 0x0e, 0x7b,
	0xc7, 0xef, 0xd4, 0xea, 0x46, 0x1b, 0x9a, 0xa5, 0x5d, 0x08, 0x40, 0x3d, 0xa6, 0x6e, 0x7a, 0xbe,
	0xa3, 0x4e, 0x15, 0xeb, 0x57, 0x6a, 0x85, 0x34, 0xa0, 0x36, 0x66, 0xc3, 0x73, 0xb5, 0xda, 0x19,
	0xc2, 0x3c, 0x4f, 0xce, 0x92, 0x73, 0x4b, 0x9e, 0xea, 0x62, 0x56, 0xf5, 0x7c, 0x56, 0xf5, 0xab,
	0x77, 0x4b, 0xfb, 0xfd, 0xf5, 0xd9, 0x6a, 0x65, 0xbd, 0xb9, 0xbd, 0x32, 0xe1, 0x56, 0x49, 0x8e,
	0x31, 0xc7, 0x5d, 0xd2, 0xea, 0xbc, 0x86, 0x19, 0x79, 0x87, 0xc8, 0x93, 0x1b, 0xea, 0xe5, 0xa1,
	0xd2, 0xbe, 0x71, 0x6d, 0xc5, 0xc8, 0xf9, 0x59, 0xa8, 0xbc, 0x55, 0x77, 0x85, 0x7e, 0xcf, 0x43,
	0x25, 0xbf, 0x63, 0x40, 0x7d, 0x4c, 0x71, 0xc4, 0xdc, 0xbb, 0x22, 0x7f, 0xc8, 0x82, 0x1e, 0x15,
	0x05, 0x5d, 0x7f, 0x86, 0x0c, 0xa9, 0xd4, 0xf9, 0x08, 0x2d, 0xb1, 0xb2, 0xee, 0x59, 0xd0, 0x4f,
	0xa9, 0xbd, 0x2c, 0xb5, 0xaf, 0xbd, 0x22, 0xc6, 0xbc, 0x90, 0x93, 0xc3, 0x54, 0xd2, 0xbf, 0x67,
	0xd5, 0xbf, 0xee, 0xa7, 0x2f, 0x67, 0xb0, 0x43, 0x81, 0x88, 0xd3, 0x3e, 0xf3, 0x83, 0xcb, 0x23,
	0x7f, 0x3c, 0x61, 0x8f, 0xe2, 0x25, 0xd0, 0xfe, 0xc8, 0x2d, 0xae, 0xbc, 0x22, 0x25, 0x82, 0xa1,
	0x26, 0xd7, 0x90, 0xbd, 0xed, 0x0f, 0x2f, 0x3d, 0x1f, 0x47, 0xe9, 0x50, 0x77, 0xd8, 0xb8, 0x8d,
	0x4e, 0xe8, 0x04, 0x2c, 0x75, 0xc5, 0xeb, 0xef, 0x6c, 0x79, 0x34, 0xdc, 0x12, 0xff, 0x0a, 0xfe,
	0x7d, 0xc3, 0xbf, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x25, 0x0e, 0x63, 0x7d, 0x3f, 0x06, 0x00,
	0x00,
}
