// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tcncloud/protoc-gen-state/state/options.proto

/*
Package state is a generated protocol buffer package.

It is generated from these files:
	github.com/tcncloud/protoc-gen-state/state/options.proto

It has these top-level messages:
	StringFieldOptions
	IntFieldOptions
*/
package state

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringFieldOptions struct {
	Create           *string `protobuf:"bytes,1,opt,name=create" json:"create,omitempty"`
	Get              *string `protobuf:"bytes,2,opt,name=get" json:"get,omitempty"`
	List             *string `protobuf:"bytes,3,opt,name=list" json:"list,omitempty"`
	Update           *string `protobuf:"bytes,4,opt,name=update" json:"update,omitempty"`
	Delete           *string `protobuf:"bytes,5,opt,name=delete" json:"delete,omitempty"`
	Custom           *string `protobuf:"bytes,6,opt,name=custom" json:"custom,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StringFieldOptions) Reset()                    { *m = StringFieldOptions{} }
func (m *StringFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*StringFieldOptions) ProtoMessage()               {}
func (*StringFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StringFieldOptions) GetCreate() string {
	if m != nil && m.Create != nil {
		return *m.Create
	}
	return ""
}

func (m *StringFieldOptions) GetGet() string {
	if m != nil && m.Get != nil {
		return *m.Get
	}
	return ""
}

func (m *StringFieldOptions) GetList() string {
	if m != nil && m.List != nil {
		return *m.List
	}
	return ""
}

func (m *StringFieldOptions) GetUpdate() string {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return ""
}

func (m *StringFieldOptions) GetDelete() string {
	if m != nil && m.Delete != nil {
		return *m.Delete
	}
	return ""
}

func (m *StringFieldOptions) GetCustom() string {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return ""
}

type IntFieldOptions struct {
	Create           *int64 `protobuf:"varint,1,opt,name=create" json:"create,omitempty"`
	Get              *int64 `protobuf:"varint,2,opt,name=get" json:"get,omitempty"`
	List             *int64 `protobuf:"varint,3,opt,name=list" json:"list,omitempty"`
	Update           *int64 `protobuf:"varint,4,opt,name=update" json:"update,omitempty"`
	Delete           *int64 `protobuf:"varint,5,opt,name=delete" json:"delete,omitempty"`
	Custom           *int64 `protobuf:"varint,6,opt,name=custom" json:"custom,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IntFieldOptions) Reset()                    { *m = IntFieldOptions{} }
func (m *IntFieldOptions) String() string            { return proto.CompactTextString(m) }
func (*IntFieldOptions) ProtoMessage()               {}
func (*IntFieldOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IntFieldOptions) GetCreate() int64 {
	if m != nil && m.Create != nil {
		return *m.Create
	}
	return 0
}

func (m *IntFieldOptions) GetGet() int64 {
	if m != nil && m.Get != nil {
		return *m.Get
	}
	return 0
}

func (m *IntFieldOptions) GetList() int64 {
	if m != nil && m.List != nil {
		return *m.List
	}
	return 0
}

func (m *IntFieldOptions) GetUpdate() int64 {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return 0
}

func (m *IntFieldOptions) GetDelete() int64 {
	if m != nil && m.Delete != nil {
		return *m.Delete
	}
	return 0
}

func (m *IntFieldOptions) GetCustom() int64 {
	if m != nil && m.Custom != nil {
		return *m.Custom
	}
	return 0
}

var E_Timeout = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550001,
	Name:          "state.timeout",
	Tag:           "varint,550001,opt,name=timeout",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Retries = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550002,
	Name:          "state.retries",
	Tag:           "varint,550002,opt,name=retries",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Method = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*StringFieldOptions)(nil),
	Field:         550003,
	Name:          "state.method",
	Tag:           "bytes,550003,opt,name=method",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_MethodTimeout = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*IntFieldOptions)(nil),
	Field:         550004,
	Name:          "state.method_timeout",
	Tag:           "bytes,550004,opt,name=method_timeout,json=methodTimeout",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_MethodRetries = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*IntFieldOptions)(nil),
	Field:         550005,
	Name:          "state.method_retries",
	Tag:           "bytes,550005,opt,name=method_retries,json=methodRetries",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_DefaultTimeout = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550006,
	Name:          "state.default_timeout",
	Tag:           "varint,550006,opt,name=default_timeout,json=defaultTimeout",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_DefaultRetries = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550007,
	Name:          "state.default_retries",
	Tag:           "varint,550007,opt,name=default_retries,json=defaultRetries",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Debug = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         550008,
	Name:          "state.debug",
	Tag:           "varint,550008,opt,name=debug",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Port = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550010,
	Name:          "state.port",
	Tag:           "varint,550010,opt,name=port",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Debounce = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*int64)(nil),
	Field:         550011,
	Name:          "state.debounce",
	Tag:           "varint,550011,opt,name=debounce",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_ProtocTsPath = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550012,
	Name:          "state.protoc_ts_path",
	Tag:           "bytes,550012,opt,name=protoc_ts_path,json=protocTsPath",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_Hostname = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550013,
	Name:          "state.hostname",
	Tag:           "bytes,550013,opt,name=hostname",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_HostnameLocation = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550014,
	Name:          "state.hostname_location",
	Tag:           "bytes,550014,opt,name=hostname_location,json=hostnameLocation",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

var E_AuthTokenLocation = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         550015,
	Name:          "state.auth_token_location",
	Tag:           "bytes,550015,opt,name=auth_token_location,json=authTokenLocation",
	Filename:      "github.com/tcncloud/protoc-gen-state/state/options.proto",
}

func init() {
	proto.RegisterType((*StringFieldOptions)(nil), "state.StringFieldOptions")
	proto.RegisterType((*IntFieldOptions)(nil), "state.IntFieldOptions")
	proto.RegisterExtension(E_Timeout)
	proto.RegisterExtension(E_Retries)
	proto.RegisterExtension(E_Method)
	proto.RegisterExtension(E_MethodTimeout)
	proto.RegisterExtension(E_MethodRetries)
	proto.RegisterExtension(E_DefaultTimeout)
	proto.RegisterExtension(E_DefaultRetries)
	proto.RegisterExtension(E_Debug)
	proto.RegisterExtension(E_Port)
	proto.RegisterExtension(E_Debounce)
	proto.RegisterExtension(E_ProtocTsPath)
	proto.RegisterExtension(E_Hostname)
	proto.RegisterExtension(E_HostnameLocation)
	proto.RegisterExtension(E_AuthTokenLocation)
}

func init() {
	proto.RegisterFile("github.com/tcncloud/protoc-gen-state/state/options.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0xdd, 0x6a, 0xd4, 0x40,
	0x14, 0xc7, 0x59, 0xb3, 0xbb, 0xb6, 0xa3, 0x6e, 0xdb, 0x08, 0x25, 0x8a, 0x42, 0xed, 0x95, 0x37,
	0xcd, 0xca, 0xe2, 0x85, 0x8e, 0x77, 0x22, 0x8a, 0x28, 0x2a, 0x71, 0xaf, 0xbc, 0x30, 0x24, 0x99,
	0xd3, 0x24, 0x98, 0x64, 0x42, 0xe6, 0xcc, 0xb3, 0x08, 0x3e, 0x91, 0xaf, 0xe3, 0xb7, 0xf8, 0xcd,
	0x7c, 0xad, 0xa5, 0xdd, 0x36, 0xb9, 0x09, 0x33, 0x67, 0xcf, 0xef, 0x37, 0xff, 0x39, 0x59, 0x42,
	0xee, 0xe4, 0x25, 0x16, 0x32, 0x0d, 0x33, 0x5e, 0xcf, 0x31, 0x6b, 0xb2, 0x8a, 0x4b, 0x36, 0x6f,
	0x3b, 0x8e, 0x3c, 0x3b, 0xc8, 0xa1, 0x39, 0x10, 0x98, 0x20, 0xcc, 0xcd, 0x93, 0xb7, 0x58, 0xf2,
	0x46, 0x84, 0xfa, 0x67, 0x7f, 0xa2, 0x8b, 0x57, 0xf7, 0x72, 0xce, 0xf3, 0x0a, 0x0c, 0x93, 0xca,
	0xc3, 0x39, 0x03, 0x91, 0x75, 0x65, 0x8b, 0xbc, 0x33, 0x8d, 0xfb, 0xef, 0x46, 0xc4, 0x7f, 0x89,
	0x5d, 0xd9, 0xe4, 0x0f, 0x4b, 0xa8, 0xd8, 0x73, 0x63, 0xf1, 0x77, 0xc9, 0x34, 0xeb, 0x20, 0x41,
	0x08, 0x46, 0x7b, 0xa3, 0x9b, 0x9b, 0x91, 0xdd, 0xf9, 0xdb, 0xc4, 0xcb, 0x01, 0x83, 0x73, 0xba,
	0xa8, 0x96, 0xbe, 0x4f, 0xc6, 0x55, 0x29, 0x30, 0xf0, 0x74, 0x49, 0xaf, 0x15, 0x2d, 0x5b, 0xa6,
	0xe8, 0xb1, 0xa1, 0xcd, 0x4e, 0xd5, 0x19, 0x54, 0x80, 0x10, 0x4c, 0x4c, 0xdd, 0xec, 0xf4, 0x69,
	0x52, 0x20, 0xaf, 0x83, 0xa9, 0x3d, 0x4d, 0xef, 0xf6, 0xdf, 0x8e, 0xc8, 0xd6, 0xe3, 0x06, 0xcf,
	0x48, 0xe6, 0xad, 0x4b, 0xe6, 0x9d, 0x4c, 0xe6, 0xad, 0x4d, 0xe6, 0x9d, 0x92, 0xcc, 0x3b, 0x25,
	0x99, 0xe7, 0x92, 0xd1, 0xbb, 0xe4, 0x3c, 0x96, 0x35, 0x70, 0x89, 0xfe, 0xf5, 0xd0, 0x0c, 0x39,
	0x74, 0x43, 0x0e, 0x8f, 0xe6, 0x0d, 0x3e, 0xbc, 0xbf, 0xa1, 0x49, 0xd7, 0xaf, 0xd0, 0x0e, 0xb0,
	0x2b, 0x41, 0xf4, 0xa1, 0x1f, 0x1d, 0x6a, 0xfb, 0x69, 0x44, 0xa6, 0x35, 0x60, 0xc1, 0x59, 0x1f,
	0xf9, 0x49, 0x93, 0x17, 0x16, 0x57, 0x42, 0xfd, 0x3f, 0x08, 0x4f, 0xbe, 0xe1, 0xc8, 0x9a, 0xe8,
	0x6b, 0x32, 0x33, 0xab, 0x78, 0xe0, 0x85, 0x3e, 0x5b, 0xf7, 0xae, 0x75, 0x1f, 0x7b, 0x41, 0xd1,
	0x25, 0xa3, 0x5b, 0xda, 0xeb, 0xfe, 0xf7, 0x0f, 0xbc, 0xf5, 0x97, 0x61, 0xfe, 0xc8, 0xce, 0xe4,
	0x11, 0xd9, 0x62, 0x70, 0x98, 0xc8, 0x0a, 0x57, 0x17, 0xb8, 0xb6, 0xe6, 0x80, 0x0a, 0x9c, 0xff,
	0xab, 0x9d, 0xea, 0xcc, 0x62, 0x2e, 0xe8, 0x11, 0x91, 0x4b, 0x7a, 0xb6, 0xe8, 0xdb, 0x31, 0x91,
	0x4b, 0x74, 0x9b, 0x4c, 0x18, 0xa4, 0x32, 0xef, 0xc1, 0xbf, 0x6b, 0x7c, 0x23, 0x32, 0xcd, 0x74,
	0x41, 0xc6, 0x2d, 0xef, 0xfa, 0xc2, 0xff, 0xb0, 0x67, 0xea, 0x5e, 0x4a, 0xc9, 0x06, 0x83, 0x94,
	0xcb, 0x26, 0x83, 0x1e, 0xee, 0xa7, 0xe5, 0x56, 0xfd, 0xf4, 0x01, 0x99, 0x99, 0x2f, 0x49, 0x8c,
	0x22, 0x6e, 0x13, 0x2c, 0x7a, 0x0c, 0xbf, 0xb4, 0x61, 0x33, 0xba, 0x68, 0xa8, 0xa5, 0x78, 0x91,
	0x60, 0xa1, 0x12, 0x14, 0x5c, 0x60, 0x93, 0xd4, 0x7d, 0x09, 0x7e, 0x5b, 0x7e, 0xd5, 0x4f, 0x9f,
	0x90, 0x1d, 0xb7, 0x8e, 0x2b, 0x9e, 0x25, 0xaa, 0xaf, 0x47, 0xf2, 0xc7, 0x4a, 0xb6, 0x1d, 0xf8,
	0xd4, 0x72, 0xf4, 0x19, 0xb9, 0x9c, 0x48, 0x2c, 0x62, 0xe4, 0x6f, 0xa0, 0x19, 0xaa, 0xfb, 0x6b,
	0x75, 0x3b, 0x0a, 0x5d, 0x2a, 0xd2, 0xf9, 0xee, 0x2f, 0x5e, 0xdd, 0x1a, 0xfe, 0xf1, 0xbd, 0xa7,
	0x9f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x32, 0x03, 0xdc, 0xaf, 0x05, 0x00, 0x00,
}
